### PR TITLE
Added missing commas

### PR DESCRIPTION
**Pull request by CoreyJ87**
This was causing the issue I added [here.](https://github.com/flypenguin/puppet-teamcity/issues/5) Hopefully you are still around to approve it.

### CODE REVIEW

**Comment by flypenguin** [comment]
sure I am :) . no idea how that could happen. should write tests more often. (although I thought I used this once ... weird).
merged.

**Comment by flypenguin** [comment]
pushed to the forge as well.

**Comment by CoreyJ87** [comment]
Awesome awesome awesome. This saved me a WHOLE bunch of time. So I was sad when it errored. Glad to see you are still around to merge this lol. Thanks man.

**Comment by flypenguin** [comment]
no worries :) . really glad it helped!

**Pull request merged**
